@startuml
skinparam defaultFontName Segoe UI
skinparam BackgroundColor EDEDED
skinparam shadowing false
skinparam RoundCorner 20
skinparam ArrowColor 454645
skinparam FontColor 454645
skinparam SequenceLifeLineBorderColor 454645
skinparam SequenceGroupHeaderFontColor 454645
skinparam SequenceGroupFontColor 454645
skinparam SequenceGroupBorderColor 454645
skinparam SequenceGroupBorderThickness 1
skinparam sequenceDivider {
    BorderColor 454645
    BorderThickness 1
    FontColor 454645
}
skinparam participant {
    BackgroundColor ffd060
    BorderColor 454645
    FontColor Black
    BorderThickness 1.5
}
skinparam database {
    BackgroundColor 98DDDE
    BorderColor 454645
    FontColor 454645
}
skinparam entity {
    BackgroundColor FFDA29
    BorderColor 454645
    FontColor 454645
}
skinparam note {
    BackgroundColor LightYellow
    BorderColor 454645
    FontColor 454645
    BorderThickness 1
}
skinparam actor {
    BackgroundColor 454645
    BorderColor 454645
    FontColor 454645
}
skinparam boundary {
    BackgroundColor FFDA29
    BorderColor 454645
    FontColor 454645
}
skinparam control {
    BackgroundColor FFDA29
    BorderColor 454645
    FontColor 454645
}
skinparam collections {
    BackgroundColor FF6F61
    BorderColor 454645
    FontColor 454645
    BorderThickness 1.5
}
skinparam queue {
    BackgroundColor FF6F61
    BorderColor 454645
    FontColor FFF
    BorderThickness 1.5
}
participant App
note right of App
  memo 1
end note
App -> AppManager : action0
        AppManager -> OtherSDK: action0(param0)
        OtherSDK -> OtherSDK: action1.action0
alt action1 exist
    OtherSDK -> SecondModule: action1 params
else not exist
    OtherSDK -> SecondModule: action2 : action3 : params
end    
SecondModule -->> App : onCallback
@enduml

@startuml
listfonts
@enduml
